export {
  type TabItem,
  Tabs,
  type TabsAnimatedConfig,
  type TabsClassNames,
  type TabsEditTarget,
  type TabsExtraContent,
  type TabsIndicatorAlign,
  type TabsIndicatorConfig,
  type TabsPlacement,
  type TabsProps,
  type TabsSemanticName,
  type TabsSize,
  type TabsStyles,
  type TabsType,
} from "./tabs.js";
