export {
  Skeleton,
  type SkeletonAvatarConfig,
  type SkeletonAvatarProps,
  type SkeletonAvatarShape,
  type SkeletonButtonProps,
  type SkeletonButtonShape,
  type SkeletonClassNames,
  type SkeletonElementClassNames,
  type SkeletonElementSemanticName,
  type SkeletonElementStyles,
  type SkeletonImageProps,
  type SkeletonInputProps,
  type SkeletonNodeProps,
  type SkeletonParagraphProps,
  type SkeletonProps,
  type SkeletonSemanticName,
  type SkeletonSize,
  type SkeletonStyles,
  type SkeletonTitleProps,
  type SkeletonWidth,
} from "./skeleton.js";
