export {
  type CapabilityAuthority,
  CapabilityBroker,
  CapabilityBrokerError,
  type CapabilityBrokerLimits,
  type CapabilityBrokerOptions,
  type CapabilityDefinition,
  type CapabilityExecutionContext,
  type CapabilityGrant,
  CapabilityInvocation,
  type CapabilityInvocationContext,
  type CapabilityInvocationOptions,
  DEFAULT_CAPABILITY_BROKER_LIMITS,
} from "./capability-broker.js";
export {
  CORE_PLUGIN_CAPABILITIES,
  type CommentCreateCapabilityInput,
  CommentCreateCapabilityInputSchema,
  type CoreCapabilityServices,
  createCoreCapabilityDefinitions,
  type ProjectCreateCapabilityInput,
  ProjectCreateCapabilityInputSchema,
  type ProjectUpdateCapabilityInput,
  ProjectUpdateCapabilityInputSchema,
  type TaskCreateCapabilityInput,
  TaskCreateCapabilityInputSchema,
  type TaskGetCapabilityInput,
  TaskGetCapabilityInputSchema,
  type TaskUpdateCapabilityInput,
  TaskUpdateCapabilityInputSchema,
} from "./core-capabilities.js";
export {
  type EnabledExtensionPackage,
  type ExtensionRegistryDiagnostic,
  type ExtensionRegistryPackage,
  type ExtensionRegistryScope,
  type ResolvedActionContribution,
  type ResolvedExtensionRegistry,
  type ResolvedFieldContribution,
  type ResolvedNavigationContribution,
  type ResolvedPageContribution,
  type ResolvedPanelContribution,
  type ResolvedRouteContribution,
  type ResolvedSettingsContribution,
  resolveExtensionRegistry,
  stableContributionId,
} from "./registry.js";
