export {
  type MessageArgsProps,
  type MessageClassNames,
  type MessageConfig,
  type MessageInstance,
  type MessageKey,
  type MessageMethod,
  type MessageSemanticName,
  type MessageStackConfig,
  type MessageStyles,
  type MessageType,
  type MessageTypeName,
  message,
  useMessage,
} from "./message.js";
