import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  PLUGIN_PREVIEW_API_VERSION,
  PLUGIN_PROTOCOL_VERSION,
  type PluginSourceManifest,
} from "@launchpp/plugin-protocol";

import { readPluginManifest } from "./project.js";

export const GENERATED_ARTIFACT_PATH = "src/generated/launchpp.ts";
export const PLUGIN_CLI_VERSION = "0.0.0";

function canonical(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value !== null && typeof value === "object") {
    return `{${Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function union(values: readonly string[]): string {
  return values.length === 0 ? "never" : values.map((value) => JSON.stringify(value)).join(" | ");
}

function clientMethods(
  manifest: PluginSourceManifest,
  domain: "comments" | "projects" | "tasks",
): readonly string[] {
  const permissions = new Set(manifest.permissions);
  if (domain === "projects") {
    return [
      ...(permissions.has("projects:read") ? ["list"] : []),
      ...(permissions.has("projects:write") ? ["create", "update"] : []),
    ];
  }
  if (domain === "tasks") {
    return [
      ...(permissions.has("tasks:read") ? ["get", "list"] : []),
      ...(permissions.has("tasks:write") ? ["create", "update"] : []),
    ];
  }
  return [
    ...(permissions.has("comments:read") ? ["list"] : []),
    ...(permissions.has("comments:write") ? ["create"] : []),
  ];
}

function fixtureSurfaceId(manifest: PluginSourceManifest): string {
  return Object.keys(manifest.browser?.surfaces ?? {}).sort()[0] ?? "fixture-surface";
}

export function renderGeneratedArtifact(manifest: PluginSourceManifest): string {
  const inputHash = createHash("sha256").update(canonical(manifest)).digest("hex");
  const surfaceIds = Object.keys(manifest.browser?.surfaces ?? {}).sort();
  const handlerIds = Object.keys(manifest.server?.handlers ?? {}).sort();
  const contributionIds = [
    ...(manifest.contributes?.actions ?? []).map(({ id }) => id),
    ...(manifest.contributes?.pages ?? []).map(({ id }) => id),
    ...(manifest.contributes?.panels ?? []).map(({ id }) => id),
    ...(manifest.contributes?.settings ?? []).map(({ id }) => id),
    ...(manifest.contributes?.taskFields ?? []).map(({ id }) => id),
  ].sort();
  const domains = (["projects", "tasks", "comments"] as const)
    .map((domain) => [domain, clientMethods(manifest, domain)] as const)
    .filter(([, methods]) => methods.length > 0);
  const clientTypeNames = {
    comments: "CommentClient",
    projects: "ProjectClient",
    tasks: "TaskClient",
  } as const;
  const clientFields = domains
    .map(
      ([domain, methods]) =>
        `  readonly ${domain}: Pick<${clientTypeNames[domain]}, ${methods
          .map((method) => JSON.stringify(method))
          .join(" | ")}>;`,
    )
    .join("\n");
  const clientValues = domains.map(([domain]) => `    ${domain}: client.${domain},`).join("\n");

  return `/* This file is generated by @launchpp/cli ${PLUGIN_CLI_VERSION}. Do not edit.\n * Protocol: ${PLUGIN_PROTOCOL_VERSION}; API: ${PLUGIN_PREVIEW_API_VERSION}; Input SHA-256: ${inputHash}\n */
import type { PluginContext } from "@launchpp/plugin-protocol";
import type {
  CommentClient,
  CommandClient,
  LaunchppClient,
  NavigationClient,
  ProjectClient,
  TaskClient,
} from "@launchpp/sdk";

export const launchppDefinition = ${JSON.stringify(
    {
      contributionIds,
      handlerIds,
      permissions: [...manifest.permissions].sort(),
      pluginId: manifest.id,
      surfaceIds,
    },
    null,
    2,
  )} as const;

export type LaunchppContributionId = ${union(contributionIds)};
export type LaunchppHandlerId = ${union(handlerIds)};
export type LaunchppPermission = ${union([...manifest.permissions].sort())};
export type LaunchppSurfaceId = ${union(surfaceIds)};

export interface LaunchppGeneratedContext extends PluginContext {
  readonly pluginId: ${JSON.stringify(manifest.id)};
}

export interface LaunchppGeneratedClient {
  readonly commands: CommandClient;
  readonly context: LaunchppGeneratedContext;
  readonly navigation: NavigationClient;
${clientFields ? `${clientFields}\n` : ""}}

export function createLaunchppGeneratedClient(client: LaunchppClient): LaunchppGeneratedClient {
  return Object.freeze({
    commands: client.commands,
    context: client.context as LaunchppGeneratedContext,
    navigation: client.navigation,
${clientValues ? `${clientValues}\n` : ""}  });
}

export const launchppFixtures: Readonly<{
  context: PluginContext;
  project: Readonly<{ id: string; name: string; organizationId: string }>;
  task: Readonly<{ id: string; projectId: string; reference: string; title: string }>;
}> = Object.freeze({
  context: {
    actor: { id: "fixture-user" },
    grantedPermissions: ${JSON.stringify([...manifest.permissions].sort())},
    installationId: "fixture-installation",
    locale: "en",
    organization: { id: "fixture-organization" },
    pluginId: ${JSON.stringify(manifest.id)},
    project: { id: "fixture-project" },
    surfaceId: ${JSON.stringify(fixtureSurfaceId(manifest))},
    theme: { id: "launchpp-light", mode: "light", tokens: {} },
  },
  project: {
    id: "fixture-project",
    name: "Plugin fixture project",
    organizationId: "fixture-organization",
  },
  task: {
    id: "fixture-task",
    projectId: "fixture-project",
    reference: "FIX-1",
    title: "Plugin fixture task",
  },
});
`;
}

export interface GeneratePluginArtifactsOptions {
  readonly projectDirectory?: string;
}

export interface GeneratedArtifactResult {
  readonly changed: boolean;
  readonly contents: string;
  readonly file: string;
}

export async function generatePluginArtifacts(
  options: GeneratePluginArtifactsOptions = {},
): Promise<GeneratedArtifactResult> {
  const projectDirectory = path.resolve(options.projectDirectory ?? process.cwd());
  const manifest = await readPluginManifest(projectDirectory);
  const contents = renderGeneratedArtifact(manifest);
  const file = path.join(projectDirectory, GENERATED_ARTIFACT_PATH);
  let current: string | undefined;
  try {
    current = await readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (current === contents) return { changed: false, contents, file };
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, contents, "utf8");
  return { changed: true, contents, file };
}
